language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g typescript
  - npm install codecov -g
install:
  - npm install
script:
  - npm run lint
  - npm run cover
  - npm run build
  - npm run doc-gen
  - npm run patch
after_success:
  - codecov
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "TravisCI"
  - git config --local user.email "samuraitruong@hotmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: npm
    email: "samuraitruong@hotmail.com"
    api_key: 
      secure: Zt++CYkqHP7mYZRtD2c2ZBxPIDqqztSTJrAZtLrxLBC8O2ZYtHTgWGJIW91KYveT2dGIycj2WutkFhQbkb52TeAxemUi4xrZzU2XySUvvHelAbpW0WneQOc+UQA4N6InfnUD+NXeIR0CrW1KFCRB4awORmIVwWZK3c2buQS5wQ76uILFJmztrYJPgP7sFnDjWYTX5tziT+hRK17qlW19pq5lslGn+NPHTdYKSHM0JQVuvZBxdIFFA7iBK1uRPSImwNJsum2+FnbscqCi5eK52OOQBfXk62wM+Xvwko7XHN3L1G1jB3ccyzaeAtA654YqEUIuaVaFIprAdmJEWhvgY2WLnyjnXEnagSunvdiYdwGvW8HkM3YMlwxUWFLfRKIiOblEs4pT/0xfbFuD1nt2nZuhUURNQd3oPxjg4T2c076SrGzxg2AJpPbcx0ZXactK1gl9sgQvTrm/V77pW5pzcTScoZ+GCCTfir9XQQEzG5JdgYwCZVx1ZpqD/SwkHUXpHY76+lgUW8brvBEbLczdHwod01wPrtptBv6aUD73mxEnS2a6P/UqQSxM/F1xOSneo9oJjViWhK/qh8JTXdvjw7cwtpqyXeNEVc/9M6KHRm3t4peASKNCqnV7qipf5V7B0t2zpvrwr5asNHo+OcNLA8ZjKlPeLADuIL8kflkW1xI=
    skip_cleanup: true
    on:
      tags: false
      branch: develop
  - provider: pages
    local-dir: doc
    skip-cleanup: true
    github-token:
      secure: "hCvE5Yx1ldUJ24J7PzIYrb2FJierQJCWUpNBRnsD9PamPnJHQ4+FXENrcF3NSeYhDB4lOJV2/5FC69ldvRVg7W+SnGcqf5/EHr5ErimGJwmUW1U/oW6cP0pFhWQqsF7zKmjiyqGUK9Nrjqg9Ep7neXWNpaJ0+eCNtoEr71IBK1WNiz0X8J3mWkVjA+z6bEmOaUcFnEfazQI36qU6C9Bg5fSw9RbLTEGtaSR/0taSn7Pl6mYtniIN49+fe5itGHKm9Wjr03C1gxViiFkVs5PQmnDSYiLm8Ef8SxaYa6V85zh13urD4rn7YMQLnF8w1ET9sF26sEsDZ/8wLYLdRPRLq5m4vQT9KfUu8w8mX0lPGt2Ekyk0oi9qOSkP2kM5vVslZlalqOIgXeSakBhMS/j00tCufm3ZQud1AueYs2S4cTnD6WeAo4NrJCTqSIz7sYRpsa4ES2TOLI+dGXqjZQX4rI+d2zYcWt36Ld/EDn1bwKmI7E+zWSb0s5mEhW6aV1NGRZbnSfzXUA613ERoW0oRm2FbjL5kXfysMRFXfjUpCSKagH+25NPraa9j/VLtkRLiKzmKaYf07umgjlGbq7EC2o88Z1GXwyLOIH+/6/6e5wOGGZNDN2vhJkr2ofkp0jP+vPNzWmGxEg39ARiiWtQSwoXlI5kunBVNcN8ixRMvD8w="
    keep-history: true
    on:
      branch: develop
notifications:
  webhooks:
    urls:
      - "https://us-central1-build-status-light-bulb.cloudfunctions.net/http"
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always